# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0002_auto_20160219_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='#000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
