# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0004_auto_20160227_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warmth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
