# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0006_auto_20160228_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dressingManage.Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='quantity3',
        ),
        migrations.AddField(
            model_name='clothe',
            name='quantities',
            field=models.ManyToManyField(to='dressingManage.Quantity'),
        ),
    ]
