# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0007_auto_20160228_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressingManage.Color'),
        ),
    ]
