# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0008_auto_20160301_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='photo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
