# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0009_auto_20160301_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
