# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0010_auto_20160303_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
