# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0012_auto_20160304_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='userOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
