# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0013_auto_20160304_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='themes',
            field=models.ManyToManyField(null=True, to='dressingManage.Theme'),
        ),
    ]
