# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0014_auto_20160304_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='themes',
            field=models.ManyToManyField(to='dressingManage.Theme'),
        ),
    ]
