# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 18:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0015_auto_20160304_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='layer',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
