# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0016_category_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wearing', models.NullBooleanField()),
                ('clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dressingManage.Clothe')),
            ],
        ),
    ]
