# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0018_outfitstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfitstorage',
            name='userOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
