# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0019_auto_20160308_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='color',
            new_name='colors',
        ),
    ]
