# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0020_auto_20160309_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitstorage',
            name='generating',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
