# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0021_outfitstorage_generating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='clothes',
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
    ]
