# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0024_auto_20160318_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='clothes',
        ),
        migrations.AddField(
            model_name='outfit',
            name='clothes',
            field=models.ManyToManyField(blank=True, null=True, to='dressingManage.Clothe'),
        ),
    ]
