# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0026_auto_20160318_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='firstLayer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstLayer_outfit', to='dressingManage.Clothe'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='nbrLayer',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='secondLayer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondLayer_outfit', to='dressingManage.Clothe'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='userOwner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
