# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0027_auto_20160318_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='temp',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='weather',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
