# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dressingManage', '0029_auto_20160318_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='theme',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dressingManage.Theme'),
        ),
    ]
